// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oidc.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c196f3560f1afc3, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SessionBackend struct {
	CookieSession        string   `protobuf:"bytes,1,opt,name=cookie_session,json=cookieSession,proto3" json:"cookie_session,omitempty"`
	CookiePath           string   `protobuf:"bytes,2,opt,name=cookie_path,json=cookiePath,proto3" json:"cookie_path,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionBackend) Reset()         { *m = SessionBackend{} }
func (m *SessionBackend) String() string { return proto.CompactTextString(m) }
func (*SessionBackend) ProtoMessage()    {}
func (*SessionBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c196f3560f1afc3, []int{1}
}

func (m *SessionBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionBackend.Unmarshal(m, b)
}
func (m *SessionBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionBackend.Marshal(b, m, deterministic)
}
func (m *SessionBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionBackend.Merge(m, src)
}
func (m *SessionBackend) XXX_Size() int {
	return xxx_messageInfo_SessionBackend.Size(m)
}
func (m *SessionBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionBackend.DiscardUnknown(m)
}

var xxx_messageInfo_SessionBackend proto.InternalMessageInfo

func (m *SessionBackend) GetCookieSession() string {
	if m != nil {
		return m.CookieSession
	}
	return ""
}

func (m *SessionBackend) GetCookiePath() string {
	if m != nil {
		return m.CookiePath
	}
	return ""
}

func (m *SessionBackend) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type SessionIdp struct {
	// mutually exclusive
	CookieState          string   `protobuf:"bytes,1,opt,name=cookie_state,json=cookieState,proto3" json:"cookie_state,omitempty"`
	CookiePath           string   `protobuf:"bytes,2,opt,name=cookie_path,json=cookiePath,proto3" json:"cookie_path,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionIdp) Reset()         { *m = SessionIdp{} }
func (m *SessionIdp) String() string { return proto.CompactTextString(m) }
func (*SessionIdp) ProtoMessage()    {}
func (*SessionIdp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c196f3560f1afc3, []int{2}
}

func (m *SessionIdp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionIdp.Unmarshal(m, b)
}
func (m *SessionIdp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionIdp.Marshal(b, m, deterministic)
}
func (m *SessionIdp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionIdp.Merge(m, src)
}
func (m *SessionIdp) XXX_Size() int {
	return xxx_messageInfo_SessionIdp.Size(m)
}
func (m *SessionIdp) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionIdp.DiscardUnknown(m)
}

var xxx_messageInfo_SessionIdp proto.InternalMessageInfo

func (m *SessionIdp) GetCookieState() string {
	if m != nil {
		return m.CookieState
	}
	return ""
}

func (m *SessionIdp) GetCookiePath() string {
	if m != nil {
		return m.CookiePath
	}
	return ""
}

func (m *SessionIdp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// login password OR login oauth
//message LoginData {
type IdpRequest struct {
	//
	//string username = 1;
	//string password = 2;
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdpRequest) Reset()         { *m = IdpRequest{} }
func (m *IdpRequest) String() string { return proto.CompactTextString(m) }
func (*IdpRequest) ProtoMessage()    {}
func (*IdpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c196f3560f1afc3, []int{3}
}

func (m *IdpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdpRequest.Unmarshal(m, b)
}
func (m *IdpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdpRequest.Marshal(b, m, deterministic)
}
func (m *IdpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdpRequest.Merge(m, src)
}
func (m *IdpRequest) XXX_Size() int {
	return xxx_messageInfo_IdpRequest.Size(m)
}
func (m *IdpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdpRequest proto.InternalMessageInfo

func (m *IdpRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

//message OidcData {
type IdpResponse struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription     string   `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdpResponse) Reset()         { *m = IdpResponse{} }
func (m *IdpResponse) String() string { return proto.CompactTextString(m) }
func (*IdpResponse) ProtoMessage()    {}
func (*IdpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c196f3560f1afc3, []int{4}
}

func (m *IdpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdpResponse.Unmarshal(m, b)
}
func (m *IdpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdpResponse.Marshal(b, m, deterministic)
}
func (m *IdpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdpResponse.Merge(m, src)
}
func (m *IdpResponse) XXX_Size() int {
	return xxx_messageInfo_IdpResponse.Size(m)
}
func (m *IdpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdpResponse proto.InternalMessageInfo

func (m *IdpResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *IdpResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IdpResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *IdpResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "main.Empty")
	proto.RegisterType((*SessionBackend)(nil), "main.SessionBackend")
	proto.RegisterType((*SessionIdp)(nil), "main.SessionIdp")
	proto.RegisterType((*IdpRequest)(nil), "main.IdpRequest")
	proto.RegisterType((*IdpResponse)(nil), "main.IdpResponse")
}

func init() { proto.RegisterFile("oidc.proto", fileDescriptor_3c196f3560f1afc3) }

var fileDescriptor_3c196f3560f1afc3 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xdd, 0x6a, 0x1a, 0x41,
	0x14, 0x46, 0x5d, 0xad, 0x3d, 0xb6, 0xa2, 0xa7, 0x5e, 0x6c, 0x97, 0x42, 0xdb, 0x85, 0x82, 0x50,
	0x70, 0xa1, 0x7d, 0x83, 0x98, 0x04, 0x84, 0x40, 0x82, 0x3e, 0x80, 0x8c, 0x3b, 0x83, 0x4e, 0x5c,
	0xe7, 0x4c, 0x66, 0xc6, 0x40, 0x12, 0x72, 0x93, 0x57, 0xf0, 0xd1, 0xf2, 0x0a, 0x79, 0x90, 0xb0,
	0xb3, 0x63, 0x34, 0xb7, 0xb9, 0x3b, 0xe7, 0x3b, 0xdf, 0x7c, 0xdf, 0xf9, 0x19, 0x00, 0x92, 0x3c,
	0x1f, 0x69, 0x43, 0x8e, 0x30, 0xda, 0x30, 0xa9, 0x92, 0x1f, 0x4b, 0xa2, 0x65, 0x21, 0x32, 0xa6,
	0x65, 0xc6, 0x94, 0x22, 0xc7, 0x9c, 0x24, 0x65, 0x2b, 0x4e, 0xfa, 0x09, 0x9a, 0x67, 0x1b, 0xed,
	0xee, 0xd2, 0x6b, 0xe8, 0xce, 0x84, 0xb5, 0x92, 0xd4, 0x09, 0xcb, 0xd7, 0x42, 0x71, 0xfc, 0x03,
	0xdd, 0x9c, 0x68, 0x2d, 0xc5, 0xdc, 0x56, 0x85, 0xb8, 0xf6, 0xab, 0x36, 0xfc, 0x3c, 0xfd, 0x5a,
	0xa1, 0x81, 0x8d, 0x3f, 0xa1, 0x13, 0x68, 0x9a, 0xb9, 0x55, 0x5c, 0xf7, 0x1c, 0xa8, 0xa0, 0x2b,
	0xe6, 0x56, 0xd8, 0x83, 0xc6, 0xd6, 0x14, 0x71, 0xc3, 0x17, 0xca, 0x30, 0x5d, 0x00, 0x84, 0xd7,
	0x13, 0xae, 0xf1, 0x37, 0x7c, 0xd9, 0xfb, 0x38, 0xe6, 0x44, 0x70, 0x09, 0xa2, 0xb3, 0x12, 0xfa,
	0x88, 0xc7, 0x10, 0x60, 0xc2, 0xf5, 0x54, 0xdc, 0x6c, 0x85, 0x75, 0x98, 0x40, 0x5b, 0x1b, 0xba,
	0x95, 0x5c, 0x98, 0xa0, 0xff, 0x96, 0xa7, 0xf7, 0xd0, 0xf1, 0x4c, 0xab, 0x49, 0x59, 0x81, 0x03,
	0x68, 0x1e, 0xf7, 0x51, 0x25, 0x88, 0x10, 0xe5, 0xc4, 0x45, 0xb0, 0xf6, 0x71, 0xc9, 0x14, 0xc6,
	0x90, 0x09, 0xb6, 0x55, 0x82, 0x7f, 0xa1, 0xef, 0x83, 0x39, 0x17, 0x36, 0x37, 0x52, 0x97, 0xdb,
	0x8e, 0x23, 0xcf, 0xe8, 0xf9, 0xc2, 0xe9, 0x01, 0xff, 0xb7, 0xab, 0x41, 0x74, 0x29, 0x79, 0x8e,
	0xe7, 0xd0, 0xbc, 0xa0, 0xa5, 0x54, 0xd8, 0x1b, 0x95, 0x57, 0x1b, 0x1d, 0x7a, 0x4f, 0x02, 0x72,
	0xd8, 0x58, 0xfa, 0xfd, 0xe9, 0xf9, 0x65, 0x57, 0xff, 0x86, 0xfd, 0xac, 0x28, 0xdf, 0x64, 0x0f,
	0xfb, 0x59, 0x1e, 0x71, 0x0c, 0xed, 0x31, 0x2b, 0x8a, 0x05, 0xcb, 0xd7, 0xd8, 0x3f, 0x92, 0xaa,
	0x86, 0x4b, 0x06, 0xef, 0xb4, 0xc2, 0xa5, 0xd3, 0xae, 0xd7, 0x6b, 0x63, 0x2b, 0x23, 0xb6, 0x75,
	0xab, 0x45, 0xcb, 0xff, 0x8d, 0xff, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5d, 0x8f, 0x6b,
	0x4d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OidcClient is the client API for Oidc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OidcClient interface {
	// this will be our OIDC login
	// all it does it redirect to the proper endpoint
	// in the openid provider with the created state and data appropriate to
	// the the defined provider
	// ok: redirect + session state cookie
	Login(ctx context.Context, in *IdpRequest, opts ...grpc.CallOption) (*SessionIdp, error)
	// this will be ALL providers callback.
	// reply either with Ok + SessionData
	// or ErrAuthFailed + Empty SessionData
	// ErrAuthFailed would redirect to /login-failed
	// ok: redirect + session cookie
	// err: redirect to login failed
	Callback(ctx context.Context, in *IdpResponse, opts ...grpc.CallOption) (*SessionBackend, error)
}

type oidcClient struct {
	cc *grpc.ClientConn
}

func NewOidcClient(cc *grpc.ClientConn) OidcClient {
	return &oidcClient{cc}
}

func (c *oidcClient) Login(ctx context.Context, in *IdpRequest, opts ...grpc.CallOption) (*SessionIdp, error) {
	out := new(SessionIdp)
	err := c.cc.Invoke(ctx, "/main.Oidc/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oidcClient) Callback(ctx context.Context, in *IdpResponse, opts ...grpc.CallOption) (*SessionBackend, error) {
	out := new(SessionBackend)
	err := c.cc.Invoke(ctx, "/main.Oidc/Callback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OidcServer is the server API for Oidc service.
type OidcServer interface {
	// this will be our OIDC login
	// all it does it redirect to the proper endpoint
	// in the openid provider with the created state and data appropriate to
	// the the defined provider
	// ok: redirect + session state cookie
	Login(context.Context, *IdpRequest) (*SessionIdp, error)
	// this will be ALL providers callback.
	// reply either with Ok + SessionData
	// or ErrAuthFailed + Empty SessionData
	// ErrAuthFailed would redirect to /login-failed
	// ok: redirect + session cookie
	// err: redirect to login failed
	Callback(context.Context, *IdpResponse) (*SessionBackend, error)
}

// UnimplementedOidcServer can be embedded to have forward compatible implementations.
type UnimplementedOidcServer struct {
}

func (*UnimplementedOidcServer) Login(ctx context.Context, req *IdpRequest) (*SessionIdp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedOidcServer) Callback(ctx context.Context, req *IdpResponse) (*SessionBackend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}

func RegisterOidcServer(s *grpc.Server, srv OidcServer) {
	s.RegisterService(&_Oidc_serviceDesc, srv)
}

func _Oidc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OidcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Oidc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OidcServer).Login(ctx, req.(*IdpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oidc_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OidcServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Oidc/Callback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OidcServer).Callback(ctx, req.(*IdpResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oidc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Oidc",
	HandlerType: (*OidcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Oidc_Login_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Oidc_Callback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oidc.proto",
}
